name: Create Release
on:
  push:
    # run only if a tag was pushed
    tags:
      - 'v*'
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Run integration tests to ensure release works
        run: |
          sbt -v +test
      - name: Get release version
        run: |
          version=$(cat version.sbt | cut -d '"' -f2)
          echo "version=$version" >> $GITHUB_ENV
      - name: Create jar with all dependencies included
        run: |
          sbt +assembly
          test -f ./target/scala-2.12/confluent-connector_2.12-${{ env.version }}.jar
          test -f ./target/scala-2.13/confluent-connector_2.13-${{ env.version }}.jar
      - name: Publish artifact to sonatype and release to maven repo
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          tools/publish_release.sh
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: true
          files: |
            target/scala-2.12/*.jar
            target/scala-2.13/*.jar
