name: PR Checks

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        distribution: [ 'zulu', 'temurin' ]
        java: [ '8', '11' ]
        os: [ 'ubuntu-latest' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Get release version
        run: |
           version=$(cat version.sbt | cut -d '"' -f2)
           echo "version=$version" >> $GITHUB_ENV
      - name: Create jar with all dependencies included
        run: |
           sbt +assembly
           test -f ./target/scala-2.12/confluent-connector_2.12-${{ env.version }}.jar
           test -f ./target/scala-2.13/confluent-connector_2.13-${{ env.version }}.jar
      - name: Run Tests
        run: sbt -v +test
